### ISSUE TITLE
error: use of undeclared identifier 'X509_CHECK_FLAG_NEVER_CHECK_SUBJECT'

### ISSUE THREAD

**Issue by tempodox** [savonet/ocaml-ssl#52]
I get a compiler error when updating to ssl.0.5.8:
```
> # ssl_stubs.c:1257:18: error: use of undeclared identifier 'X509_CHECK_FLAG_NEVER_CHECK_SUBJECT'
> #         flags |= X509_CHECK_FLAG_NEVER_CHECK_SUBJECT;
> #                  ^
```
That flag is not defined in `<openssl/x509v3.h>`.

**Comment by anmonteiro** [comment]
It would be helpful to know which OpenSSL version you're trying to build this against, because I'm using SSL 0.5.8 without any trouble.

**Comment by aantron** [comment]
I just observed this on WSL, with

```
$ openssl version
OpenSSL 1.0.2g  1 Mar 2016
```

And in Travis. I don't have the version in Travis handy, but can find it out. The log is [here](https://travis-ci.org/ocsigen/lwt_ssl/jobs/556900642#L334).

**Comment by anmonteiro** [comment]
It works on my side with any of the OpenSSL 1.1.1 versions that I tried

**Comment by vouillon** [comment]
This was introduced in OpenSSL 1.1.0.

**Comment by emillon** [comment]
I think that the code introduced in https://github.com/savonet/ocaml-ssl/pull/49 should be gated under a macro test like it's being done for other features in `src/config/discover.ml`.

**Comment by tempodox** [comment]
Thank you all for your help! I had indeed openssl 1.0 installed and hadn't noticed there was an upgrade to 1.1 available. After I swapped it out and rebuilt all the dependents everything seems to be working, including ocaml-ssl.0.5.8.

**Comment by thatportugueseguy** [comment]
I have this issue, too. I've tried many of the solutions online, and can't seem to make it build. I have a mac with macOS Mojave (v10.14.5) which has `libressl` installed.

I tried exporting the variables for the CPP headers from multiple from default xcode include path, which didn't work.

After that, i've installed `openssl` v1.1.1c and exported the headers info as an env variable as seen on a few issues on github, didn't work. Also tried multiple variations of this with the headers and versions of openssl, including v1.0.2.

The thing that solved my issue was pinning `ssl` to v0.5.7.

Ideally, would love to keep using libressl and have `ssl` on v0.5.8. Is there anything you can suggest? I know this issue was closed, but felt a bit wrong to open a new one with the exact same problem. Will do if needed.

Thanks in advace :)
